version: '3'
services:
  mysql:
   container_name: mysql
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_DATABASE: VolcanoCamping
    MYSQL_ROOT_PASSWORD: root
    MYSQL_ROOT_HOST: '%'
   ports:
   - "3606:3306"
   restart: always
  app:
    container_name: app
    image: williamyeh/java8
    restart: always
    volumes:
      - ../build/libs:/app
    expose:
      - "8080"
    command: java -jar /app/volcano-camping-0.0.1-SNAPSHOT.jar
    depends_on:
      - mysql